In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("./input"))

# Any results you write to the current directory are saved as output.

['Breast_cancer_data.csv']


# **Artificial Neural Network (ANN)**

**In this kernel, artificial neural network (ANN) concept has been explained and implemented by using Keras. **

In [23]:
data = pd.read_csv('./input/Breast_cancer_data.csv')
data.head(10)

mean_square_of_filed(sq.hectare)  number_of_days_watered(percentage)  \
0                             17.99                               10.38   
1                             20.57                               17.77   
2                             19.69                               21.25   
3                             11.42                               20.38   
4                             20.29                               14.34   
5                             12.45                               15.70   
6                             18.25                               19.98   
7                             13.71                               20.83   
8                             13.00                               21.82   
9                             12.46                               24.04   

   pest_ratio  annual_fee  lost_profit(percentage)  private/public   
0      122.80      1001.0                  0.11840                0  
1      132.90      1326.0                  0.08474                0  
2      130.00      1203.0                  0.10960                0  
3       77.58       386.1                  0.14250                0  
4      135.10      1297.0                  0.10030                0  
5       82.57       477.1                  0.12780                0  
6      119.60      1040.0                  0.09463                0  
7       90.20       577.9                  0.11890                0  
8       87.50       519.8                  0.12730                0  
9       83.97       475.9                  0.11860                0

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   mean_square_of_filed(sq.hectare)    569 non-null    float64
 1   number_of_days_watered(percentage)  569 non-null    float64
 2   pest_ratio                          569 non-null    float64
 3   annual_fee                          569 non-null    float64
 4   lost_profit(percentage)             569 non-null    float64
 5   private/public                      569 non-null    int64  
dtypes: float64(5), int64(1)
memory usage: 26.8 KB


In [25]:
smoothness = data['lost_profit(percentage)'] > 1.0
smoothness.values

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [26]:
X = data.iloc[:,0:5].values
Y = data.iloc[:,5].values

In [27]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

*  **In artificial neural network method, independent variables namely input data must be in interval [0,1].**

*  **Therefore, input data sets must be scaled.**

In [28]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

# Artificial Neural Network (ANN)

* Artificial neural networks are one of the main tools used in machine learning. 
* As the “neural” part of their name suggests, they are brain-inspired systems which are intended to replicate the way that we humans learn. 
* Neural networks consist of input and output layers, as well as (in most cases) a hidden layer consisting of units that transform the input into something that the output layer can use. 
* They are excellent tools for finding patterns which are far too complex or numerous for a human programmer to extract and teach the machine to recognize. 
* Neural networks also called “perceptrons”.
* Neural networks have become a major part of artificial intelligence in the last several decades. This is due to the arrival of a technique called “backpropagation,” which allows networks to adjust their hidden layers of neurons in situations where the outcome doesn’t match what the creator is hoping for.

In [29]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

# Hidden layers and input layer are  added.
classifier.add(Dense(3, kernel_initializer="uniform", activation = 'relu', input_dim = 5))

classifier.add(Dense(3, kernel_initializer="uniform", activation = 'relu'))

# Output layer
classifier.add(Dense(1, kernel_initializer="uniform", activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, epochs = 50)

# Prediction
y_pred = classifier.predict(X_test)

Epoch 1/50
12/12 [==============================] - 1s 2ms/step - loss: 0.6925 - accuracy: 0.5984
Epoch 2/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6914 - accuracy: 0.6194
Epoch 3/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6902 - accuracy: 0.6194
Epoch 4/50
12/12 [==============================] - 0s 1ms/step - loss: 0.6893 - accuracy: 0.6194
Epoch 5/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6882 - accuracy: 0.6194
Epoch 6/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6874 - accuracy: 0.6194
Epoch 7/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6864 - accuracy: 0.6194
Epoch 8/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6855 - accuracy: 0.6194
Epoch 9/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6846 - accuracy: 0.6194
Epoch 10/50
12/12 [==============================] - 0s 2ms/step - loss: 0.6838 - accuracy: 0.6194
Epoch 11/50
12/12 [

In [30]:
y_pred

array([[0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.58317924],
       [0.583

In [31]:
y_pred = (y_pred > 0.5)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[  0,  67],
       [  0, 121]], dtype=int64)

# Conclusion

As per the result of confusion matrix, breast cancer predictions are quite successful. We can say that artificial neural network is a good algorithm for this data set. 

My last shared kernels are here:

https://www.kaggle.com/armagansarikey/wine-quality-prediction-with-pca-lda-algorithms

https://www.kaggle.com/armagansarikey/natural-language-processing-nlp-project

If you have any question or suggest, I will be happy to hear it.

If you like it, please upvote :)